import React, { useCallback, useEffect, useMemo, useState } from "react";
import Swal from "sweetalert2";
import api from "../api";
import { useInstitution } from "../institution/InstitutionContext";
import "./AlumniEngagement.css";

const getRoles=()=>{try{const a=JSON.parse(localStorage.getItem("roles")||"[]");const b=localStorage.getItem("userRole");return(a.length?a:[b]).filter(Boolean).map(x=>String(x).toLowerCase());}catch(_){return[String(localStorage.getItem("userRole")||"").toLowerCase()].filter(Boolean);}};
const MANAGERS=new Set(["department_hod","principal","academic_coordinator","coordinator","frontoffice","placement_officer","admin","superadmin","super_admin"]);
const STAFF=new Set(["teacher",...MANAGERS]);
const human=v=>String(v||"").replace(/_/g," ").replace(/\b\w/g,m=>m.toUpperCase());
const dt=v=>v?new Date(v).toLocaleString([], {dateStyle:"medium",timeStyle:"short"}):"—";
const d=v=>v?new Date(`${String(v).slice(0,10)}T00:00:00`).toLocaleDateString([], {dateStyle:"medium"}):"—";

export default function AlumniEngagement(){
  const roles=getRoles(); const staff=roles.some(r=>STAFF.has(r)); const manager=roles.some(r=>MANAGERS.has(r));
  return <Workspace staff={staff} manager={manager}/>;
}

function Workspace({staff,manager}){
  const {isCollege}=useInstitution();
  const [loading,setLoading]=useState(true),[tab,setTab]=useState("overview");
  const [meta,setMeta]=useState({classes:[],sections:[]}),[dash,setDash]=useState({counts:{},years:[]}),[profiles,setProfiles]=useState([]),[events,setEvents]=useState([]),[opps,setOpps]=useState([]),[mentorships,setMentorships]=useState([]),[me,setMe]=useState(null),[students,setStudents]=useState([]);
  const [query,setQuery]=useState(""),[mentorOnly,setMentorOnly]=useState(false),[selectedIds,setSelectedIds]=useState([]),[passingYear,setPassingYear]=useState(new Date().getFullYear());
  const load=useCallback(async()=>{setLoading(true);try{
    const calls=[api.get("/alumni-engagement/meta"),api.get("/alumni-engagement/dashboard"),api.get("/alumni-engagement/directory"),api.get("/alumni-engagement/events"),api.get("/alumni-engagement/opportunities"),api.get("/alumni-engagement/mentorships")];
    const [m,da,di,ev,op,mt]=await Promise.all(calls);setMeta(m.data||{});setDash(da.data||{});setProfiles(di.data?.profiles||[]);setEvents(ev.data?.events||[]);setOpps(op.data?.opportunities||[]);setMentorships(mt.data?.mentorships||[]);
    if(!staff){const mine=await api.get("/alumni-engagement/me").catch(()=>({data:null}));setMe(mine.data||null);}
    if(manager){const st=await api.get("/alumni-engagement/students");setStudents(st.data?.students||[]);}
  }catch(e){Swal.fire("Unable to load",e.response?.data?.message||e.message,"error");}finally{setLoading(false);}},[staff,manager]);
  useEffect(()=>{load();},[load]);
  const filtered=useMemo(()=>profiles.filter(p=>{const q=query.trim().toLowerCase();if(mentorOnly&&!p.mentor_opt_in)return false;return!q||`${p.full_name} ${p.current_company||""} ${p.designation||""} ${p.course_label||""} ${p.passing_year||""}`.toLowerCase().includes(q);}),[profiles,query,mentorOnly]);
  if(loading)return <div className="container-fluid py-5 text-center"><span className="spinner-border spinner-border-sm me-2"/>Loading alumni network…</div>;
  const labels={title:isCollege?"Alumni & Engagement":"Former Students & Alumni",person:isCollege?"Alumni":"Former Student",course:isCollege?"Program / Semester":"Class / Batch"};
  const tabs=["overview","directory","events","opportunities","mentorships",...(manager?["convert"]:[])];
  return <div className="container-fluid py-4 alumni-page">
    <Hero isCollege={isCollege}/>
    <div className="alumni-tabs mb-4">{tabs.map(x=><button key={x} className={tab===x?"active":""} onClick={()=>setTab(x)}>{x==="convert"?`Convert ${labels.person}s`:human(x)}</button>)}</div>
    {tab==="overview"&&<Overview dash={dash} isCollege={isCollege} me={me} staff={staff} events={events} opps={opps}/>} 
    {tab==="directory"&&<Directory rows={filtered} query={query} setQuery={setQuery} mentorOnly={mentorOnly} setMentorOnly={setMentorOnly} me={me} staff={staff} onRequest={async(p)=>{const {value}=await Swal.fire({title:`Request mentoring from ${p.full_name}`,input:"textarea",inputLabel:"What guidance do you need?",showCancelButton:true,confirmButtonText:"Send request"});if(value!==undefined){try{await api.post("/alumni-engagement/mentorships",{alumni_profile_id:p.id,topic:"Alumni mentoring",request_note:value});Swal.fire("Sent","Mentorship request sent.","success");load();}catch(e){Swal.fire("Unable to send",e.response?.data?.message||e.message,"error");}}}}/>}
    {tab==="events"&&<Events rows={events} staff={staff} manager={manager} hasProfile={!!me?.profile} onCreate={()=>createEvent(load)} onRsvp={async(id,response)=>{try{await api.post(`/alumni-engagement/events/${id}/rsvp`,{response});load();}catch(e){Swal.fire("Unable to RSVP",e.response?.data?.message||e.message,"error");}}}/>} 
    {tab==="opportunities"&&<Opportunities rows={opps} staff={staff} manager={manager} hasProfile={!!me?.profile} onCreate={()=>createOpportunity(load,staff)} onStatus={async(id,status)=>{try{await api.patch(`/alumni-engagement/opportunities/${id}`,{status});load();}catch(e){Swal.fire("Unable to update",e.response?.data?.message||e.message,"error");}}}/>} 
    {tab==="mentorships"&&<Mentorships rows={mentorships} me={me} manager={manager} onStatus={async(id,status)=>{try{await api.patch(`/alumni-engagement/mentorships/${id}`,{status});load();}catch(e){Swal.fire("Unable to update",e.response?.data?.message||e.message,"error");}}}/>} 
    {tab==="convert"&&manager&&<ConvertPanel students={students} selectedIds={selectedIds} setSelectedIds={setSelectedIds} passingYear={passingYear} setPassingYear={setPassingYear} labels={labels} onConvert={async()=>{if(!selectedIds.length)return Swal.fire("Select students","Choose at least one student.","warning");try{const {data}=await api.post("/alumni-engagement/profiles/convert",{student_ids:selectedIds,passing_year:Number(passingYear),directory_opt_in:true});Swal.fire("Converted",data.message||"Profiles created.","success");setSelectedIds([]);load();}catch(e){Swal.fire("Unable to convert",e.response?.data?.message||e.message,"error");}}}/>} 
    {!staff&&me?.profile&&<SelfProfile profile={me.profile} achievements={me.achievements||[]} isCollege={isCollege} onRefresh={load}/>} 
  </div>;
}

function Hero({isCollege}){return <div className="alumni-hero mb-4"><div><span>{isCollege?"College Community & Career Network":"School Community & Former Students"}</span><h1>{isCollege?"Alumni & Engagement":"Former Students & Alumni"}</h1><p>{isCollege?"Keep graduates connected through mentoring, events, achievements, career referrals and lifelong engagement.":"Build a lifelong former-student network for reunions, achievements, mentoring, career talks and community support."}</p></div><i className="bi bi-mortarboard-fill"/></div>}
function Metric({icon,label,value,tone="primary"}){return <div className="col-6 col-lg-3"><div className={`alumni-metric ${tone}`}><i className={`bi ${icon}`}/><div><strong>{value??0}</strong><small>{label}</small></div></div></div>}
function Overview({dash,isCollege,me,staff,events,opps}){const c=dash.counts||{};return <><div className="row g-3 mb-4"><Metric icon="bi-people-fill" label={isCollege?"Active Alumni":"Former Students"} value={c.total}/><Metric icon="bi-person-heart" label="Available Mentors" value={c.mentors} tone="success"/><Metric icon="bi-briefcase-fill" label="Employed / Business" value={c.employed} tone="info"/><Metric icon="bi-calendar-event" label="Upcoming Events" value={c.upcoming_events} tone="warning"/></div><div className="row g-4"><div className="col-xl-7"><div className="card border-0 shadow-sm h-100"><div className="card-body p-4"><h2 className="h5">Network Snapshot</h2><div className="row g-3 mt-1"><div className="col-md-4"><Info label="Entrepreneurs" value={c.entrepreneurs||0}/></div><div className="col-md-4"><Info label="Published Opportunities" value={c.opportunities||0}/></div><div className="col-md-4"><Info label="Active Mentorships" value={c.active_mentorships||0}/></div></div><h3 className="h6 mt-4">Recent passing years</h3><div className="d-flex flex-wrap gap-2">{(dash.years||[]).map(y=><span key={y.passing_year||"na"} className="badge text-bg-light border">{y.passing_year||"Unknown"}: {y.count}</span>)}</div></div></div></div><div className="col-xl-5"><div className="card border-0 shadow-sm h-100"><div className="card-body p-4"><h2 className="h5">What’s active</h2><p className="text-muted small mb-2">{events.filter(x=>x.status==="published").length} published event(s)</p><p className="text-muted small mb-2">{opps.filter(x=>x.status==="published").length} active opportunity/referral(s)</p>{!staff&&<p className="mb-0">{me?.profile?`Your alumni profile is active${me.profile.mentor_opt_in?" and open for mentoring":""}.`:"Your alumni profile has not been activated yet. You can still explore mentors and opportunities."}</p>}</div></div></div></div></>}
function Info({label,value}){return <div className="alumni-info"><strong>{value}</strong><span>{label}</span></div>}
function Directory({rows,query,setQuery,mentorOnly,setMentorOnly,onRequest,staff}){return <div className="card border-0 shadow-sm"><div className="card-body p-4"><div className="d-flex flex-wrap justify-content-between gap-3 align-items-center mb-3"><div><h2 className="h5 mb-1">Alumni Directory</h2><p className="text-muted small mb-0">Search by name, batch, organization, designation or city.</p></div><div className="d-flex gap-2"><input className="form-control" placeholder="Search alumni…" value={query} onChange={e=>setQuery(e.target.value)}/><button className={`btn ${mentorOnly?"btn-primary":"btn-outline-primary"}`} onClick={()=>setMentorOnly(v=>!v)}>Mentors</button></div></div><div className="row g-3">{rows.map(p=><div className="col-md-6 col-xl-4" key={p.id}><div className="alumni-person h-100"><div className="d-flex justify-content-between gap-2"><div><h3>{p.full_name}</h3><small>{p.course_label||"Former Student"}{p.passing_year?` · ${p.passing_year}`:""}</small></div>{p.mentor_opt_in&&<span className="badge text-bg-success align-self-start">Mentor</span>}</div><p className="mb-1 mt-3"><strong>{p.designation||p.employment_status||"Alumni"}</strong>{p.current_company?` · ${p.current_company}`:""}</p><p className="text-muted small">{[p.current_city,p.current_country].filter(Boolean).join(", ")||"Location not shared"}</p>{p.bio&&<p className="small alumni-bio">{p.bio}</p>}<div className="d-flex flex-wrap gap-2">{p.linkedin_url&&<a className="btn btn-sm btn-outline-secondary" href={p.linkedin_url} target="_blank" rel="noreferrer">LinkedIn</a>}{p.email&&<a className="btn btn-sm btn-outline-secondary" href={`mailto:${p.email}`}>Email</a>}{p.mentor_opt_in&&!staff&&<button className="btn btn-sm btn-primary" onClick={()=>onRequest(p)}>Request Mentoring</button>}</div>{(p.achievements||[]).slice(0,2).map(a=><div className="alumni-achievement" key={a.id}><i className="bi bi-award"/> {a.title}</div>)}</div></div>)}{!rows.length&&<Empty text="No alumni profiles match the current filters."/>}</div></div></div>}
function Events({rows,manager,hasProfile,onCreate,onRsvp}){return <div className="card border-0 shadow-sm"><div className="card-body p-4"><div className="d-flex justify-content-between mb-3"><div><h2 className="h5">Events & Reunions</h2><p className="text-muted small mb-0">Alumni meets, reunions, webinars, guest lectures and networking events.</p></div>{manager&&<button className="btn btn-primary" onClick={onCreate}>+ Create Event</button>}</div>{rows.map(x=><div className="alumni-list-row" key={x.id}><div><strong>{x.title}</strong><small>{human(x.event_type)} · {dt(x.starts_at)} · {x.venue||"Venue TBA"}</small><p>{x.description}</p></div><div className="text-end"><span className={`badge ${x.status==="published"?"text-bg-success":"text-bg-secondary"}`}>{human(x.status)}</span><small className="d-block mt-2">{x.rsvp_summary?.going||0} going</small>{hasProfile&&x.status==="published"&&<div className="btn-group btn-group-sm mt-2"><button className="btn btn-outline-success" onClick={()=>onRsvp(x.id,"going")}>Going</button><button className="btn btn-outline-secondary" onClick={()=>onRsvp(x.id,"maybe")}>Maybe</button></div>}</div></div>)}{!rows.length&&<Empty text="No alumni events yet."/>}</div></div>}
function Opportunities({rows,manager,hasProfile,onCreate,onStatus}){return <div className="card border-0 shadow-sm"><div className="card-body p-4"><div className="d-flex justify-content-between mb-3"><div><h2 className="h5">Career & Community Opportunities</h2><p className="text-muted small mb-0">Job referrals, internships, career talks, scholarships and other alumni opportunities.</p></div>{(manager||hasProfile)&&<button className="btn btn-primary" onClick={onCreate}>+ Share Opportunity</button>}</div>{rows.map(x=><div className="alumni-list-row" key={x.id}><div><strong>{x.title}</strong><small>{human(x.opportunity_type)} · {x.organization||"Community"}{x.deadline?` · Deadline ${d(x.deadline)}`:""}</small><p>{x.description}</p>{x.alumni&&<small>Shared by {x.alumni.full_name}</small>}</div><div className="text-end"><span className={`badge ${x.status==="published"?"text-bg-success":x.status==="pending"?"text-bg-warning":"text-bg-secondary"}`}>{human(x.status)}</span>{x.apply_url&&x.status==="published"&&<a className="btn btn-sm btn-outline-primary d-block mt-2" href={x.apply_url} target="_blank" rel="noreferrer">Open Link</a>}{manager&&x.status==="pending"&&<button className="btn btn-sm btn-success d-block mt-2" onClick={()=>onStatus(x.id,"published")}>Approve</button>}</div></div>)}{!rows.length&&<Empty text="No opportunities have been shared yet."/>}</div></div>}
function Mentorships({rows,me,manager,onStatus}){return <div className="card border-0 shadow-sm"><div className="card-body p-4"><h2 className="h5">Alumni Mentorship</h2><p className="text-muted small">Connect current students with former students for academic, career and professional guidance.</p>{rows.map(x=><div className="alumni-list-row" key={x.id}><div><strong>{x.topic}</strong><small>{x.student?.name||"Student"} ↔ {x.alumni?.full_name||"Alumni Mentor"}</small><p>{x.request_note}</p></div><div className="text-end"><span className="badge text-bg-light border">{human(x.status)}</span>{(manager||me?.profile?.id===x.alumni_profile_id)&&x.status==="requested"&&<button className="btn btn-sm btn-success d-block mt-2" onClick={()=>onStatus(x.id,"accepted")}>Accept</button>}{(manager||me?.profile?.id===x.alumni_profile_id)&&["accepted","active"].includes(x.status)&&<button className="btn btn-sm btn-outline-primary d-block mt-2" onClick={()=>onStatus(x.id,"completed")}>Complete</button>}</div></div>)}{!rows.length&&<Empty text="No mentorship connections yet."/>}</div></div>}
function ConvertPanel({students,selectedIds,setSelectedIds,passingYear,setPassingYear,labels,onConvert}){const toggle=id=>setSelectedIds(a=>a.includes(id)?a.filter(x=>x!==id):[...a,id]);return <div className="card border-0 shadow-sm"><div className="card-body p-4"><div className="row g-3 align-items-end mb-3"><div className="col-md-4"><label className="form-label">Passing Year</label><input type="number" className="form-control" value={passingYear} onChange={e=>setPassingYear(e.target.value)}/></div><div className="col-md-8 text-md-end"><button className="btn btn-primary" onClick={onConvert}>Convert Selected ({selectedIds.length})</button></div></div><div className="table-responsive"><table className="table align-middle"><thead><tr><th></th><th>Student</th><th>{labels.course}</th><th>Admission No.</th></tr></thead><tbody>{students.map(s=><tr key={s.id}><td><input type="checkbox" checked={selectedIds.includes(s.id)} onChange={()=>toggle(s.id)}/></td><td><strong>{s.name}</strong></td><td>{s.Class?.class_name||"—"} {s.Section?.section_name?`· ${s.Section.section_name}`:""}</td><td>{s.admission_number||"—"}</td></tr>)}</tbody></table></div>{!students.length&&<Empty text={`No students are available for ${labels.person.toLowerCase()} conversion.`}/>}</div></div>}
function SelfProfile({profile,achievements,isCollege,onRefresh}){const edit=async()=>{const {value:v}=await Swal.fire({title:"Update Alumni Profile",html:`<input id="a-company" class="swal2-input" placeholder="Current company" value="${profile.current_company||""}"><input id="a-designation" class="swal2-input" placeholder="Designation" value="${profile.designation||""}"><input id="a-city" class="swal2-input" placeholder="Current city" value="${profile.current_city||""}"><input id="a-linkedin" class="swal2-input" placeholder="LinkedIn URL" value="${profile.linkedin_url||""}"><textarea id="a-bio" class="swal2-textarea" placeholder="Short bio">${profile.bio||""}</textarea><label><input id="a-mentor" type="checkbox" ${profile.mentor_opt_in?"checked":""}> Available as a mentor</label>`,showCancelButton:true,preConfirm:()=>({current_company:document.getElementById("a-company").value,designation:document.getElementById("a-designation").value,current_city:document.getElementById("a-city").value,linkedin_url:document.getElementById("a-linkedin").value,bio:document.getElementById("a-bio").value,mentor_opt_in:document.getElementById("a-mentor").checked})});if(v){await api.patch(`/alumni-engagement/profiles/${profile.id}`,v);onRefresh();}};const achievement=async()=>{const {value:title}=await Swal.fire({title:"Add Achievement",input:"text",inputLabel:"Achievement / Award",showCancelButton:true});if(title){await api.post(`/alumni-engagement/profiles/${profile.id}/achievements`,{title});onRefresh();}};return <div className="card border-0 shadow-sm mt-4"><div className="card-body p-4"><div className="d-flex justify-content-between"><div><h2 className="h5">My {isCollege?"Alumni":"Former Student"} Profile</h2><p className="text-muted small">Keep your career, location, mentoring preference and achievements current.</p></div><div className="d-flex gap-2"><button className="btn btn-outline-primary" onClick={achievement}>+ Achievement</button><button className="btn btn-primary" onClick={edit}>Edit Profile</button></div></div><div className="row g-3"><div className="col-md-4"><Info label="Batch" value={profile.passing_year||profile.passing_batch||"—"}/></div><div className="col-md-4"><Info label="Current Organization" value={profile.current_company||"—"}/></div><div className="col-md-4"><Info label="Mentoring" value={profile.mentor_opt_in?"Available":"Not enabled"}/></div></div>{achievements.length>0&&<div className="mt-3"><strong>Achievements</strong>{achievements.map(a=><div className="alumni-achievement" key={a.id}><i className="bi bi-award-fill"/> {a.title}</div>)}</div>}</div></div>}
function Empty({text}){return <div className="text-center text-muted py-5 w-100"><i className="bi bi-inbox fs-2 d-block mb-2"/>{text}</div>}

async function createEvent(refresh){const {value:v}=await Swal.fire({title:"Create Alumni Event",html:'<input id="e-title" class="swal2-input" placeholder="Event title"><input id="e-date" type="datetime-local" class="swal2-input"><input id="e-venue" class="swal2-input" placeholder="Venue / Online link"><textarea id="e-desc" class="swal2-textarea" placeholder="Description"></textarea><label><input id="e-publish" type="checkbox" checked> Publish now</label>',showCancelButton:true,preConfirm:()=>({title:document.getElementById("e-title").value,starts_at:document.getElementById("e-date").value,venue:document.getElementById("e-venue").value,description:document.getElementById("e-desc").value,status:document.getElementById("e-publish").checked?"published":"draft"})});if(v){try{await api.post("/alumni-engagement/events",v);refresh();}catch(e){Swal.fire("Unable to create",e.response?.data?.message||e.message,"error");}}}
async function createOpportunity(refresh,staff){const {value:v}=await Swal.fire({title:"Share Opportunity",html:'<input id="o-title" class="swal2-input" placeholder="Title"><input id="o-org" class="swal2-input" placeholder="Organization"><select id="o-type" class="swal2-select"><option value="job_referral">Job Referral</option><option value="internship">Internship</option><option value="career_talk">Career Talk</option><option value="guest_lecture">Guest Lecture</option><option value="scholarship">Scholarship</option></select><input id="o-url" class="swal2-input" placeholder="Apply / details URL"><textarea id="o-desc" class="swal2-textarea" placeholder="Description"></textarea>',showCancelButton:true,preConfirm:()=>({title:document.getElementById("o-title").value,organization:document.getElementById("o-org").value,opportunity_type:document.getElementById("o-type").value,apply_url:document.getElementById("o-url").value,description:document.getElementById("o-desc").value,status:staff?"published":"pending"})});if(v){try{await api.post("/alumni-engagement/opportunities",v);refresh();}catch(e){Swal.fire("Unable to share",e.response?.data?.message||e.message,"error");}}}
