import React, { useCallback, useEffect, useMemo, useState } from "react";
import Swal from "sweetalert2";
import api from "../api";
import { useInstitution } from "../institution/InstitutionContext";
import "./CollegeGraduationDegree.css";

const roles = () => { try { const many=JSON.parse(localStorage.getItem("roles")||"[]"); const one=localStorage.getItem("userRole"); return (many.length?many:[one]).filter(Boolean).map((x)=>String(x).toLowerCase()); } catch (_) { return [String(localStorage.getItem("userRole")||"").toLowerCase()].filter(Boolean); } };
const MANAGERS=new Set(["examination","department_hod","principal","academic_coordinator","coordinator","frontoffice","front_office","accounts","account","accountant","admin","superadmin","super_admin"]);
const human=(v)=>String(v||"").replace(/_/g," ").replace(/\b\w/g,(m)=>m.toUpperCase());
const dateText=(v)=>v?new Date(v).toLocaleDateString([], { dateStyle:"medium" }):"—";
const tone=(s)=>({eligible:"success",graduated:"primary",not_eligible:"danger",pending_review:"warning",clear:"success",cleared:"success",blocked:"danger",pending:"warning",ready:"success",issued:"primary",collected:"success",dispatched:"info",processing:"warning",registered:"primary",confirmed:"success",attended:"success",published:"success",draft:"secondary"}[s]||"secondary");

export default function CollegeGraduationDegree(){
  const { isCollege }=useInstitution(); const rs=roles(); const student=rs.includes("student"); const manager=rs.some((r)=>MANAGERS.has(r));
  if(!isCollege)return <div className="container-fluid py-4"><div className="alert alert-info rounded-4">Convocation / Degree Issuance is available in College mode.</div></div>;
  if(student)return <StudentView/>;
  if(manager)return <StaffView/>;
  return <div className="container-fluid py-4"><div className="alert alert-warning rounded-4">Your role does not have access to Convocation / Degree Issuance.</div></div>;
}

function StudentView(){
  const [loading,setLoading]=useState(true),[data,setData]=useState({record:null,events:[]});
  const load=useCallback(async()=>{setLoading(true);try{const {data:d}=await api.get("/college-graduation/me");setData(d||{});}catch(e){Swal.fire("Unable to load",e.response?.data?.message||e.message,"error");}finally{setLoading(false);}},[]);
  useEffect(()=>{load();},[load]);
  const r=data.record||{}; const clearances=r.clearances||[]; const eligible=["eligible","graduated"].includes(r.eligibility_status);
  const register=async(event)=>{const x=await Swal.fire({title:"Register for Convocation",html:`<div class="text-start"><label class="form-label">Gown size</label><select id="gown" class="form-select mb-3"><option value="">Not sure</option><option>S</option><option>M</option><option>L</option><option>XL</option><option>XXL</option></select><label class="form-label">Guest count</label><input id="guests" type="number" min="0" max="10" value="0" class="form-control mb-3"><label class="form-label">Degree collection</label><select id="mode" class="form-select"><option value="in_person">In person</option><option value="postal">By post / courier</option></select></div>`,showCancelButton:true,confirmButtonText:"Register",preConfirm:()=>({gown_size:document.getElementById("gown").value,guest_count:Number(document.getElementById("guests").value||0),degree_collection_mode:document.getElementById("mode").value})}); if(!x.isConfirmed)return;try{await api.post("/college-graduation/convocation/register",{event_id:event.id,...x.value});await load();Swal.fire("Registered","Convocation registration submitted.","success");}catch(e){Swal.fire("Unable to register",e.response?.data?.message||e.message,"error");}};
  return <div className="container-fluid py-4 grad-page"><Hero title="Graduation · Convocation · Degree" subtitle="Track your graduation eligibility, no-dues, convocation registration and degree / provisional status."/>{loading?<Loading/>:<>
    <div className="row g-3 mb-4"><Metric label="Eligibility" value={human(r.eligibility_status||"pending")} icon="bi-mortarboard-fill" tone={tone(r.eligibility_status)}/><Metric label="CGPA" value={r.cgpa??"—"} icon="bi-award-fill"/><Metric label="Credits Earned" value={r.earned_credits??0} icon="bi-journal-check"/><Metric label="Pending Backlogs" value={r.pending_backlogs??0} icon="bi-arrow-counterclockwise" tone={r.pending_backlogs?"danger":"success"}/></div>
    {r.eligibility_remarks&&<div className={`alert alert-${r.eligibility_status==="eligible"||r.eligibility_status==="graduated"?"success":"warning"} rounded-4`}>{r.eligibility_remarks}</div>}
    <div className="row g-3"><div className="col-xl-7"><Card title="Eligibility & No-Dues" icon="bi-clipboard2-check-fill"><div className="row g-3 mb-3"><Info label="Academic Status" value={human(r.academic_status)}/><Info label="No-Dues Status" value={human(r.no_dues_status)}/><Info label="Required Credits" value={r.required_credits??"Not configured"}/><Info label="Project Requirement" value={r.require_project?(r.project_completed?"Completed":"Pending"):"Not required"}/><Info label="Internship Requirement" value={r.require_internship?(r.internship_completed?"Completed":"Pending"):"Not required"}/><Info label="Graduation Year" value={r.graduation_year||"—"}/></div><div className="clearance-grid">{clearances.map((c)=><div className="clearance-item" key={c.id}><div><strong>{c.label||human(c.clearance_type)}</strong>{c.remarks&&<small>{c.remarks}</small>}</div><span className={`badge text-bg-${tone(c.status)}`}>{human(c.status)}</span></div>)}</div></Card></div>
    <div className="col-xl-5"><Card title="Degree & Provisional" icon="bi-patch-check-fill"><StatusLine label="Provisional" status={r.provisional_status} detail={r.provisional_number}/><StatusLine label="Degree" status={r.degree_status} detail={r.degree_number}/><Info label="Degree Issue Date" value={dateText(r.degree_issue_date)}/><Info label="Collection Mode" value={human(r.degree_collection_mode)||"—"}/>{r.dispatch_tracking&&<Info label="Dispatch Tracking" value={r.dispatch_tracking}/>}</Card></div></div>
    <Card title="Convocation" icon="bi-calendar-event-fill" className="mt-3"><div className="row g-3">{r.convocationEvent&&<div className="col-lg-5"><div className="convocation-current"><span className={`badge text-bg-${tone(r.convocation_status)}`}>{human(r.convocation_status)}</span><h5>{r.convocationEvent.title}</h5><p><i className="bi bi-calendar3 me-2"/>{dateText(r.convocationEvent.ceremony_date)}</p><p><i className="bi bi-geo-alt me-2"/>{r.convocationEvent.venue||"Venue to be announced"}</p>{r.seat_number&&<p><strong>Seat:</strong> {r.seat_number} {r.ceremony_batch?`· ${r.ceremony_batch}`:""}</p>}</div></div>}<div className={r.convocationEvent?"col-lg-7":"col-12"}><div className="event-list">{(data.events||[]).length?(data.events||[]).map((e)=><div className="event-row" key={e.id}><div><strong>{e.title}</strong><small>{dateText(e.ceremony_date)} · {e.venue||"Venue TBA"}</small></div>{eligible&&Number(r.convocation_event_id)!==Number(e.id)&&<button className="btn btn-sm btn-primary" onClick={()=>register(e)}>Register</button>}</div>):<div className="text-muted">No published convocation event is open right now.</div>}</div></div></div></Card>
  </>}</div>;
}

function StaffView(){
  const [loading,setLoading]=useState(true),[tab,setTab]=useState("records"),[dash,setDash]=useState({counts:{},events:[]}),[records,setRecords]=useState([]),[candidates,setCandidates]=useState([]),[q,setQ]=useState(""),[selected,setSelected]=useState(null),[eventForm,setEventForm]=useState({title:"Annual Convocation",ceremony_date:"",venue:"",registration_open:"",registration_deadline:"",status:"draft"});
  const load=useCallback(async()=>{setLoading(true);try{const [d,r,c]=await Promise.all([api.get("/college-graduation/dashboard"),api.get("/college-graduation/records"),api.get("/college-graduation/candidates")]);setDash(d.data||{});setRecords(r.data?.records||[]);setCandidates(c.data?.students||[]);}catch(e){Swal.fire("Unable to load",e.response?.data?.message||e.message,"error");}finally{setLoading(false);}},[]);useEffect(()=>{load();},[load]);
  const filteredRecords=useMemo(()=>records.filter((r)=>!q||`${r.student?.name||""} ${r.student?.admission_number||""} ${r.degree_number||""}`.toLowerCase().includes(q.toLowerCase())),[records,q]);
  const filteredCandidates=useMemo(()=>candidates.filter((r)=>!q||`${r.name||""} ${r.admission_number||""} ${r.program_semester||""}`.toLowerCase().includes(q.toLowerCase())),[candidates,q]);
  const open=async(id)=>{try{const {data}=await api.get(`/college-graduation/records/${id}`);setSelected(data.record);}catch(e){Swal.fire("Unable to open",e.response?.data?.message||e.message,"error");}};
  const evaluate=async(student)=>{const x=await Swal.fire({title:`Evaluate ${student.name}`,html:`<div class="text-start"><label class="form-label">Required total credits <span class="text-muted">(optional)</span></label><input id="credits" type="number" step="0.5" class="form-control mb-3" placeholder="e.g. 120"><div class="form-check mb-2"><input id="project" class="form-check-input" type="checkbox"><label class="form-check-label" for="project">Project / dissertation required</label></div><div class="form-check"><input id="internship" class="form-check-input" type="checkbox"><label class="form-check-label" for="internship">Internship required</label></div></div>`,showCancelButton:true,confirmButtonText:"Evaluate",preConfirm:()=>({required_credits:document.getElementById("credits").value||null,require_project:document.getElementById("project").checked,require_internship:document.getElementById("internship").checked})});if(!x.isConfirmed)return;try{const {data}=await api.post(`/college-graduation/evaluate/${student.id}`,x.value);setSelected(data.record);await load();}catch(e){Swal.fire("Unable to evaluate",e.response?.data?.message||e.message,"error");}};
  const createEvent=async(e)=>{e.preventDefault();if(!eventForm.title||!eventForm.ceremony_date)return Swal.fire("Required","Title and ceremony date are required.","warning");try{await api.post("/college-graduation/events",eventForm);setEventForm({title:"Annual Convocation",ceremony_date:"",venue:"",registration_open:"",registration_deadline:"",status:"draft"});await load();Swal.fire("Created","Convocation event created.","success");}catch(err){Swal.fire("Unable to create",err.response?.data?.message||err.message,"error");}};
  const c=dash.counts||{};
  return <div className="container-fluid py-4 grad-page"><Hero title="Convocation & Degree Issuance" subtitle="Evaluate graduation eligibility, manage no-dues, convocation registration, provisional certificates and degree issuance."/><div className="row g-3 mb-4"><Metric label="Graduation Records" value={c.total||0} icon="bi-people-fill"/><Metric label="Eligible" value={c.eligible||0} icon="bi-check-circle-fill" tone="success"/><Metric label="Graduated" value={c.graduated||0} icon="bi-mortarboard-fill" tone="primary"/><Metric label="Degree Ready / Issued" value={c.degree_ready||0} icon="bi-patch-check-fill" tone="info"/></div><div className="d-flex flex-wrap gap-2 mb-3"><button className={`btn ${tab==="records"?"btn-primary":"btn-light"}`} onClick={()=>setTab("records")}>Graduation Records</button><button className={`btn ${tab==="candidates"?"btn-primary":"btn-light"}`} onClick={()=>setTab("candidates")}>Student Candidates</button><button className={`btn ${tab==="events"?"btn-primary":"btn-light"}`} onClick={()=>setTab("events")}>Convocation Events</button><div className="ms-auto grad-search"><i className="bi bi-search"/><input value={q} onChange={(e)=>setQ(e.target.value)} placeholder="Search student / degree…"/></div></div>
  {loading?<Loading/>:tab==="records"?<RecordsTable rows={filteredRecords} onOpen={open}/>:tab==="candidates"?<CandidatesTable rows={filteredCandidates} onEvaluate={evaluate}/>:<EventsPanel events={dash.events||[]} form={eventForm} setForm={setEventForm} onSubmit={createEvent}/>} {selected&&<RecordModal record={selected} setRecord={setSelected} onClose={()=>setSelected(null)} onRefresh={async()=>{await open(selected.id);await load();}}/>}</div>;
}

function RecordModal({record,setRecord,onClose,onRefresh}){
  const updateRequirements=async()=>{const x=await Swal.fire({title:"Graduation Requirements",html:`<div class="text-start"><label class="form-label">Required credits</label><input id="credits" type="number" step="0.5" value="${record.required_credits??""}" class="form-control mb-3"><div class="form-check mb-2"><input id="project" class="form-check-input" type="checkbox" ${record.require_project?"checked":""}><label class="form-check-label">Project required</label></div><div class="form-check"><input id="internship" class="form-check-input" type="checkbox" ${record.require_internship?"checked":""}><label class="form-check-label">Internship required</label></div></div>`,showCancelButton:true,confirmButtonText:"Save & Recalculate",preConfirm:()=>({required_credits:document.getElementById("credits").value||null,require_project:document.getElementById("project").checked,require_internship:document.getElementById("internship").checked})});if(!x.isConfirmed)return;try{const {data}=await api.patch(`/college-graduation/records/${record.id}`,x.value);setRecord(data.record);onRefresh();}catch(e){Swal.fire("Unable to update",e.response?.data?.message||e.message,"error");}};
  const clearance=async(c,status)=>{let remarks="";if(status==="blocked"){const x=await Swal.fire({title:`Block ${c.label}`,input:"textarea",inputLabel:"Reason",showCancelButton:true});if(!x.isConfirmed)return;remarks=x.value||"";}try{const {data}=await api.patch(`/college-graduation/records/${record.id}/clearances/${c.clearance_type}`,{status,remarks});setRecord(data.record);onRefresh();}catch(e){Swal.fire("Unable to update",e.response?.data?.message||e.message,"error");}};
  const clearAll=async()=>{const x=await Swal.fire({title:"Mark all No-Dues clear?",icon:"question",showCancelButton:true,confirmButtonText:"Clear all"});if(!x.isConfirmed)return;try{const {data}=await api.post(`/college-graduation/records/${record.id}/clear-all`,{});setRecord(data.record);onRefresh();}catch(e){Swal.fire("Unable to update",e.response?.data?.message||e.message,"error");}};
  const graduate=async()=>{const x=await Swal.fire({title:"Finalize Graduation?",text:"This can also activate the Alumni profile.",icon:"question",showCancelButton:true,confirmButtonText:"Mark Graduated"});if(!x.isConfirmed)return;try{const {data}=await api.post(`/college-graduation/records/${record.id}/graduated`,{convert_to_alumni:true});setRecord(data.record);onRefresh();Swal.fire("Graduated","Graduation finalized and alumni profile activated where available.","success");}catch(e){Swal.fire("Cannot finalize",e.response?.data?.message||e.message,"warning");}};
  const degree=async()=>{const x=await Swal.fire({title:"Degree / Provisional Status",width:720,html:`<div class="text-start row g-2"><div class="col-md-6"><label class="form-label">Provisional status</label><select id="ps" class="form-select"><option>not_ready</option><option>processing</option><option>ready</option><option>issued</option></select></div><div class="col-md-6"><label class="form-label">Provisional number</label><input id="pn" class="form-control" value="${record.provisional_number||""}"></div><div class="col-md-6"><label class="form-label">Provisional issue date</label><input id="pid" type="date" class="form-control" value="${record.provisional_issue_date||""}"></div><div class="col-md-6"><label class="form-label">Degree status</label><select id="ds" class="form-select"><option>not_ready</option><option>processing</option><option>ready</option><option>issued</option><option>collected</option><option>dispatched</option></select></div><div class="col-md-6"><label class="form-label">Degree number / serial</label><input id="dn" class="form-control" value="${record.degree_number||""}"></div><div class="col-md-6"><label class="form-label">Degree issue date</label><input id="did" type="date" class="form-control" value="${record.degree_issue_date||""}"></div><div class="col-md-6"><label class="form-label">Collection mode</label><select id="mode" class="form-select"><option value="">Not set</option><option value="in_person">In person</option><option value="postal">Post / Courier</option></select></div><div class="col-md-6"><label class="form-label">Dispatch tracking</label><input id="track" class="form-control" value="${record.dispatch_tracking||""}"></div></div>`,showCancelButton:true,confirmButtonText:"Save",didOpen:()=>{document.getElementById("ps").value=record.provisional_status||"not_ready";document.getElementById("ds").value=record.degree_status||"not_ready";document.getElementById("mode").value=record.degree_collection_mode||"";},preConfirm:()=>({provisional_status:document.getElementById("ps").value,provisional_number:document.getElementById("pn").value,provisional_issue_date:document.getElementById("pid").value||null,degree_status:document.getElementById("ds").value,degree_number:document.getElementById("dn").value,degree_issue_date:document.getElementById("did").value||null,degree_collection_mode:document.getElementById("mode").value||null,dispatch_tracking:document.getElementById("track").value||null})});if(!x.isConfirmed)return;try{const {data}=await api.patch(`/college-graduation/records/${record.id}/degree`,x.value);setRecord(data.record);onRefresh();}catch(e){Swal.fire("Unable to update",e.response?.data?.message||e.message,"error");}};
  const convocation=async()=>{const x=await Swal.fire({title:"Convocation Management",width:680,html:`<div class="text-start row g-2"><div class="col-md-6"><label class="form-label">Registration status</label><select id="cs" class="form-select"><option>not_registered</option><option>registered</option><option>confirmed</option><option>attended</option><option>absent</option><option>cancelled</option></select></div><div class="col-md-6"><label class="form-label">Seat number</label><input id="seat" class="form-control" value="${record.seat_number||""}"></div><div class="col-md-6"><label class="form-label">Ceremony batch</label><input id="batch" class="form-control" value="${record.ceremony_batch||""}" placeholder="e.g. Batch A · 10:00 AM"></div><div class="col-md-3"><label class="form-label">Gown size</label><input id="gown" class="form-control" value="${record.gown_size||""}"></div><div class="col-md-3"><label class="form-label">Guests</label><input id="guests" type="number" min="0" class="form-control" value="${record.guest_count||0}"></div></div>`,showCancelButton:true,confirmButtonText:"Save",didOpen:()=>{document.getElementById("cs").value=record.convocation_status||"not_registered";},preConfirm:()=>({convocation_status:document.getElementById("cs").value,seat_number:document.getElementById("seat").value||null,ceremony_batch:document.getElementById("batch").value||null,gown_size:document.getElementById("gown").value||null,guest_count:Number(document.getElementById("guests").value||0)})});if(!x.isConfirmed)return;try{const {data}=await api.patch(`/college-graduation/records/${record.id}/degree`,x.value);setRecord(data.record);onRefresh();}catch(e){Swal.fire("Unable to update",e.response?.data?.message||e.message,"error");}};
  return <div className="grad-modal"><div className="grad-dialog"><div className="d-flex justify-content-between gap-3"><div><span className={`badge text-bg-${tone(record.eligibility_status)}`}>{human(record.eligibility_status)}</span><h3 className="h4 mt-2 mb-1">{record.student?.name}</h3><div className="text-muted">{record.student?.admission_number} · {record.programSemester?.class_name||"Program / Semester"}</div></div><button className="btn-close" onClick={onClose}/></div><div className="row g-3 mt-2"><MetricMini label="CGPA" value={record.cgpa??"—"}/><MetricMini label="Credits" value={`${record.earned_credits||0}${record.required_credits?` / ${record.required_credits}`:""}`}/><MetricMini label="Backlogs" value={record.pending_backlogs||0}/><MetricMini label="No-Dues" value={human(record.no_dues_status)}/></div>{record.eligibility_remarks&&<div className="alert alert-light border mt-3 mb-0">{record.eligibility_remarks}</div>}<div className="d-flex flex-wrap gap-2 mt-3"><button className="btn btn-sm btn-outline-primary" onClick={updateRequirements}>Requirements</button><button className="btn btn-sm btn-outline-success" onClick={clearAll}>Clear All No-Dues</button>{record.eligibility_status==="eligible"&&<button className="btn btn-sm btn-success" onClick={graduate}>Mark Graduated</button>}<button className="btn btn-sm btn-outline-dark" onClick={degree}>Degree / Provisional</button><button className="btn btn-sm btn-outline-secondary" onClick={convocation}>Convocation</button></div><hr/><h5>No-Dues Clearance</h5><div className="clearance-grid">{(record.clearances||[]).map((c)=><div className="clearance-item" key={c.id}><div><strong>{c.label||human(c.clearance_type)}</strong>{c.remarks&&<small>{c.remarks}</small>}</div><div className="d-flex align-items-center gap-1"><span className={`badge text-bg-${tone(c.status)}`}>{human(c.status)}</span><button className="btn btn-sm btn-link text-success" onClick={()=>clearance(c,"cleared")}>Clear</button><button className="btn btn-sm btn-link text-danger" onClick={()=>clearance(c,"blocked")}>Block</button></div></div>)}</div><hr/><div className="row g-3"><Info label="Provisional" value={`${human(record.provisional_status)}${record.provisional_number?` · ${record.provisional_number}`:""}`}/><Info label="Degree" value={`${human(record.degree_status)}${record.degree_number?` · ${record.degree_number}`:""}`}/><Info label="Convocation" value={human(record.convocation_status)}/><Info label="University Roll" value={record.identity?.university_roll_number||"—"}/></div></div></div>;
}

function RecordsTable({rows,onOpen}){return <div className="card border-0 shadow-sm rounded-4 overflow-hidden"><div className="table-responsive"><table className="table align-middle mb-0"><thead><tr><th>Student</th><th>Academic</th><th>No-Dues</th><th>Eligibility</th><th>Degree</th><th></th></tr></thead><tbody>{rows.length?rows.map((r)=><tr key={r.id}><td><strong>{r.student?.name||`Student ${r.student_id}`}</strong><div className="small text-muted">{r.student?.admission_number||""}</div></td><td>CGPA {r.cgpa??"—"}<div className="small text-muted">{r.earned_credits||0} credits · {r.pending_backlogs||0} backlog(s)</div></td><td><span className={`badge text-bg-${tone(r.no_dues_status)}`}>{human(r.no_dues_status)}</span></td><td><span className={`badge text-bg-${tone(r.eligibility_status)}`}>{human(r.eligibility_status)}</span></td><td><span className={`badge text-bg-${tone(r.degree_status)}`}>{human(r.degree_status)}</span></td><td className="text-end"><button className="btn btn-sm btn-outline-primary" onClick={()=>onOpen(r.id)}>Open</button></td></tr>):<tr><td colSpan="6" className="text-center text-muted py-5">No graduation records yet. Evaluate candidates first.</td></tr>}</tbody></table></div></div>}
function CandidatesTable({rows,onEvaluate}){return <div className="card border-0 shadow-sm rounded-4 overflow-hidden"><div className="table-responsive"><table className="table align-middle mb-0"><thead><tr><th>Student</th><th>Program / Semester</th><th>Batch</th><th>Graduation Record</th><th></th></tr></thead><tbody>{rows.length?rows.map((s)=><tr key={s.id}><td><strong>{s.name}</strong><div className="small text-muted">{s.admission_number}</div></td><td>{s.program_semester||"—"}</td><td>{s.batch_section||"—"}</td><td>{s.graduation?<span className={`badge text-bg-${tone(s.graduation.eligibility_status)}`}>{human(s.graduation.eligibility_status)}</span>:<span className="text-muted">Not evaluated</span>}</td><td className="text-end"><button className="btn btn-sm btn-primary" onClick={()=>onEvaluate(s)}>{s.graduation?"Re-evaluate":"Evaluate"}</button></td></tr>):<tr><td colSpan="5" className="text-center text-muted py-5">No students found.</td></tr>}</tbody></table></div></div>}
function EventsPanel({events,form,setForm,onSubmit}){return <div className="row g-3"><div className="col-xl-5"><Card title="Create Convocation Event" icon="bi-calendar-plus-fill"><form onSubmit={onSubmit} className="row g-3"><div className="col-12"><label className="form-label">Title</label><input className="form-control" value={form.title} onChange={(e)=>setForm({...form,title:e.target.value})}/></div><div className="col-md-6"><label className="form-label">Ceremony date/time</label><input type="datetime-local" className="form-control" value={form.ceremony_date} onChange={(e)=>setForm({...form,ceremony_date:e.target.value})}/></div><div className="col-md-6"><label className="form-label">Venue</label><input className="form-control" value={form.venue} onChange={(e)=>setForm({...form,venue:e.target.value})}/></div><div className="col-md-6"><label className="form-label">Registration opens</label><input type="datetime-local" className="form-control" value={form.registration_open} onChange={(e)=>setForm({...form,registration_open:e.target.value})}/></div><div className="col-md-6"><label className="form-label">Deadline</label><input type="datetime-local" className="form-control" value={form.registration_deadline} onChange={(e)=>setForm({...form,registration_deadline:e.target.value})}/></div><div className="col-12"><select className="form-select" value={form.status} onChange={(e)=>setForm({...form,status:e.target.value})}><option value="draft">Draft</option><option value="published">Published</option></select></div><div className="col-12 d-grid"><button className="btn btn-primary">Create Event</button></div></form></Card></div><div className="col-xl-7"><Card title="Convocation Events" icon="bi-calendar-event-fill"><div className="event-list">{events.length?events.map((e)=><div className="event-row" key={e.id}><div><strong>{e.title}</strong><small>{dateText(e.ceremony_date)} · {e.venue||"Venue TBA"}</small></div><span className={`badge text-bg-${tone(e.status)}`}>{human(e.status)}</span></div>):<div className="text-muted">No convocation events created yet.</div>}</div></Card></div></div>}
const Hero=({title,subtitle})=><div className="grad-hero mb-4"><div><span>College Graduation Lifecycle</span><h1>{title}</h1><p>{subtitle}</p></div><i className="bi bi-mortarboard-fill"/></div>;
const Metric=({label,value,icon,tone="primary"})=><div className="col-12 col-md-6 col-xl-3"><div className="grad-metric"><i className={`bi ${icon} text-${tone}`}/><div><strong>{value}</strong><span>{label}</span></div></div></div>;
const MetricMini=({label,value})=><div className="col-6 col-lg-3"><div className="grad-mini"><small>{label}</small><strong>{value}</strong></div></div>;
const Card=({title,icon,children,className=""})=><div className={`card border-0 shadow-sm rounded-4 ${className}`}><div className="card-body p-4"><h5 className="mb-3"><i className={`bi ${icon} me-2 text-primary`}/>{title}</h5>{children}</div></div>;
const Info=({label,value})=><div className="col-md-6"><small className="text-muted d-block">{label}</small><strong>{value||"—"}</strong></div>;
const StatusLine=({label,status,detail})=><div className="status-line"><div><small>{label}</small><strong>{detail||"No number assigned"}</strong></div><span className={`badge text-bg-${tone(status)}`}>{human(status)}</span></div>;
const Loading=()=> <div className="text-center py-5 text-muted"><div className="spinner-border spinner-border-sm me-2"/>Loading graduation records…</div>;
