import React, { useEffect, useMemo, useState } from "react";
import Swal from "sweetalert2";
import api from "../api";
import "./CollegeResearch.css";

const human = (value) => String(value || "").replace(/_/g, " ").replace(/\b\w/g, (m) => m.toUpperCase());
const money = (value) => new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(Number(value || 0));
const date = (value) => value ? new Date(`${String(value).slice(0, 10)}T00:00:00`).toLocaleDateString("en-IN") : "—";
const empty = {
  publication: { publication_type: "journal_article", title: "", contributors_text: "", journal_conference: "", publisher: "", publication_date: "", academic_year: "", department_id: "", doi: "", isbn: "", issn: "", indexing: "", scopus_indexed: false, web_of_science_indexed: false, ugc_care_indexed: false, impact_factor: "", citation_count: 0, status: "submitted", verification_status: "draft", external_url: "", abstract: "" },
  project: { project_type: "funded_project", title: "", principal_investigator: "", co_investigators: "", funding_agency: "", scheme_name: "", reference_number: "", grant_category: "government", sanctioned_amount: "", received_amount: "", start_date: "", end_date: "", academic_year: "", department_id: "", status: "proposed", verification_status: "draft", summary: "", outcomes: "", external_url: "" },
  ipr: { ipr_type: "patent", title: "", inventors: "", application_number: "", filing_date: "", publication_number: "", publication_date: "", grant_number: "", grant_date: "", patent_office: "", country: "India", academic_year: "", department_id: "", status: "filed", verification_status: "draft", external_url: "", remarks: "" },
  activity: { activity_type: "conference", title: "", participant_names: "", organizer: "", venue: "", start_date: "", end_date: "", participation_role: "participant", certificate_number: "", academic_year: "", department_id: "", status: "completed", verification_status: "draft", external_url: "", remarks: "" },
};
const endpoints = { publication: "publications", project: "projects", ipr: "ipr", activity: "activities" };
const singular = { publication: "Publication", project: "Project / Grant", ipr: "Patent / IPR", activity: "Research Activity" };

export default function CollegeResearch() {
  const [active, setActive] = useState("publication");
  const [meta, setMeta] = useState({ departments: [], owners: [], permissions: {} });
  const [dashboard, setDashboard] = useState({ cards: {}, recent: [] });
  const [rows, setRows] = useState([]);
  const [loading, setLoading] = useState(true);
  const [modal, setModal] = useState(null);
  const [docs, setDocs] = useState(null);
  const [filters, setFilters] = useState({ q: "", department_id: "", academic_year: "", verification_status: "" });

  const loadMeta = async () => { const { data } = await api.get("/research-rd/meta"); setMeta(data || {}); };
  const loadDashboard = async () => { const { data } = await api.get("/research-rd/dashboard"); setDashboard(data || { cards: {}, recent: [] }); };
  const loadRows = async (kind = active) => {
    const params = Object.fromEntries(Object.entries(filters).filter(([, v]) => String(v || "").trim()));
    const { data } = await api.get(`/research-rd/${endpoints[kind]}`, { params });
    setRows(data?.rows || []);
  };
  const refresh = async (kind = active) => {
    setLoading(true);
    try { await Promise.all([loadDashboard(), loadRows(kind)]); } catch (e) { Swal.fire("Unable to load", e.response?.data?.message || e.message, "error"); }
    finally { setLoading(false); }
  };
  useEffect(() => { Promise.all([loadMeta(), loadDashboard()]).then(() => loadRows(active)).catch((e) => Swal.fire("Unable to load", e.response?.data?.message || e.message, "error")).finally(() => setLoading(false)); }, []);
  useEffect(() => { if (!loading) loadRows(active).catch(() => {}); }, [active]); // eslint-disable-line react-hooks/exhaustive-deps

  const cards = dashboard.cards || {};
  const filteredLabel = useMemo(() => ({ publication: "Publications", project: "Projects & Grants", ipr: "Patents / IPR", activity: "Conferences & FDPs" }[active]), [active]);

  const openNew = () => setModal({ kind: active, row: null, form: { ...empty[active] } });
  const openEdit = (row) => setModal({ kind: active, row, form: { ...empty[active], ...row, department_id: row.department_id || "" } });
  const save = async () => {
    if (!modal?.form?.title?.trim()) return Swal.fire("Title required", "Enter the research title.", "warning");
    try {
      const ep = endpoints[modal.kind];
      if (modal.row?.id) await api.put(`/research-rd/${ep}/${modal.row.id}`, modal.form);
      else await api.post(`/research-rd/${ep}`, modal.form);
      setModal(null); await refresh(modal.kind); Swal.fire({ icon: "success", title: "Saved", timer: 1000, showConfirmButton: false });
    } catch (e) { Swal.fire("Unable to save", e.response?.data?.message || e.message, "error"); }
  };
  const verify = async (kind, row, status) => {
    const { value: remarks } = await Swal.fire({ title: `${human(status)} record?`, input: "textarea", inputLabel: "Verification remarks (optional)", showCancelButton: true, confirmButtonText: human(status) });
    if (remarks === undefined) return;
    try { await api.post(`/research-rd/${kind}/${row.id}/verify`, { verification_status: status, verification_remarks: remarks }); await refresh(kind); }
    catch (e) { Swal.fire("Unable to verify", e.response?.data?.message || e.message, "error"); }
  };
  const openDocs = async (kind, row) => {
    try { const { data } = await api.get(`/research-rd/${kind}/${row.id}/documents`); setDocs({ kind, row, documents: data?.documents || [] }); }
    catch (e) { Swal.fire("Unable to load evidence", e.response?.data?.message || e.message, "error"); }
  };

  return <div className="container-fluid py-4 research-page">
    <div className="research-hero mb-4">
      <div><span className="research-kicker">College R&D</span><h1 className="h3 mb-2">Research & Publications</h1><p className="mb-0">Publications, funded research, patents/IPR, conferences and accreditation-ready evidence in one workspace.</p></div>
      {meta.permissions?.contributor && <button className="btn btn-light fw-semibold" onClick={openNew}><i className="bi bi-plus-lg me-2" />Add {singular[active]}</button>}
    </div>

    <div className="row g-3 mb-4">
      <Stat icon="bi-journal-richtext" label="Publications" value={cards.published ?? cards.publications ?? 0} sub={`${cards.scopus || 0} Scopus indexed`} />
      <Stat icon="bi-patch-check-fill" label="Patents Granted" value={cards.patents_granted || 0} sub="IPR outcomes" />
      <Stat icon="bi-bezier2" label="Active Projects" value={cards.active_projects || 0} sub={`${cards.completed_projects || 0} completed`} />
      <Stat icon="bi-cash-stack" label="Sanctioned Grants" value={money(cards.sanctioned_amount)} sub={`${money(cards.received_amount)} received`} wide />
    </div>

    <div className="card border-0 shadow-sm mb-3 research-filter-card"><div className="card-body"><div className="row g-2 align-items-end">
      <div className="col-md-4"><label className="form-label">Search</label><input className="form-control" placeholder="Title..." value={filters.q} onChange={(e) => setFilters({ ...filters, q: e.target.value })} /></div>
      <div className="col-md-3"><label className="form-label">Department</label><select className="form-select" value={filters.department_id} onChange={(e) => setFilters({ ...filters, department_id: e.target.value })}><option value="">All Departments</option>{(meta.departments || []).map((d) => <option key={d.id} value={d.id}>{d.name}</option>)}</select></div>
      <div className="col-md-2"><label className="form-label">Academic Year</label><input className="form-control" placeholder="2026-27" value={filters.academic_year} onChange={(e) => setFilters({ ...filters, academic_year: e.target.value })} /></div>
      <div className="col-md-2"><label className="form-label">Verification</label><select className="form-select" value={filters.verification_status} onChange={(e) => setFilters({ ...filters, verification_status: e.target.value })}><option value="">All</option>{["draft","submitted","verified","rejected"].map((x) => <option key={x} value={x}>{human(x)}</option>)}</select></div>
      <div className="col-md-1 d-grid"><button className="btn btn-primary" onClick={() => refresh(active)}><i className="bi bi-search" /></button></div>
    </div></div></div>

    <div className="research-tabs mb-3">
      {[['publication','Publications','bi-journal-richtext'],['project','Projects & Grants','bi-cash-coin'],['ipr','Patents / IPR','bi-lightbulb-fill'],['activity','Conferences / FDP','bi-easel2-fill']].map(([key,label,icon]) => <button key={key} onClick={() => setActive(key)} className={`research-tab ${active === key ? "active" : ""}`}><i className={`bi ${icon}`} />{label}</button>)}
    </div>

    <div className="card border-0 shadow-sm"><div className="card-body p-0">
      {loading ? <div className="p-5 text-center"><div className="spinner-border text-primary" /></div> : rows.length ? <div className="table-responsive"><table className="table align-middle mb-0 research-table"><thead><tr><th>Research Record</th><th>Department / Year</th><th>Status</th><th>Verification</th><th className="text-end">Actions</th></tr></thead><tbody>{rows.map((row) => <Row key={row.id} kind={active} row={row} manager={meta.permissions?.manager} canEdit={row.can_edit} onEdit={() => openEdit(row)} onDocs={() => openDocs(active,row)} onVerify={(status) => verify(active,row,status)} />)}</tbody></table></div> : <div className="research-empty"><i className="bi bi-journal-plus" /><h3>No {filteredLabel.toLowerCase()} yet</h3><p>Add the first record to start building the institution's research profile.</p>{meta.permissions?.contributor && <button className="btn btn-primary" onClick={openNew}>Add Record</button>}</div>}
    </div></div>

    {modal && <RecordModal modal={modal} setModal={setModal} meta={meta} onClose={() => setModal(null)} onSave={save} />}
    {docs && <EvidenceModal state={docs} setState={setDocs} onClose={() => setDocs(null)} />}
  </div>;
}

function Stat({ icon, label, value, sub, wide }) { return <div className={wide ? "col-12 col-md-6 col-xl-3" : "col-6 col-xl-3"}><div className="research-stat h-100"><span className="research-stat-icon"><i className={`bi ${icon}`} /></span><div><div className="research-stat-value">{value}</div><div className="research-stat-label">{label}</div><small>{sub}</small></div></div></div>; }
function Row({ kind, row, manager, canEdit, onEdit, onDocs, onVerify }) {
  const subtitle = kind === "publication" ? `${human(row.publication_type)}${row.journal_conference ? ` · ${row.journal_conference}` : ""}` : kind === "project" ? `${human(row.project_type)}${row.funding_agency ? ` · ${row.funding_agency}` : ""}` : kind === "ipr" ? `${human(row.ipr_type)}${row.application_number ? ` · ${row.application_number}` : ""}` : `${human(row.activity_type)}${row.organizer ? ` · ${row.organizer}` : ""}`;
  return <tr><td><div className="fw-semibold">{row.title}</div><div className="small text-muted mt-1">{subtitle}</div>{kind === "publication" && <div className="small mt-1">{row.scopus_indexed && <span className="badge text-bg-info me-1">Scopus</span>}{row.web_of_science_indexed && <span className="badge text-bg-dark me-1">Web of Science</span>}{row.ugc_care_indexed && <span className="badge text-bg-secondary">UGC CARE</span>}</div>}</td><td><div>{row.department?.name || "Institution-wide"}</div><small className="text-muted">{row.academic_year || "—"}</small></td><td><span className="badge rounded-pill text-bg-light border">{human(row.status)}</span></td><td><span className={`badge rounded-pill ${row.verification_status === "verified" ? "text-bg-success" : row.verification_status === "rejected" ? "text-bg-danger" : row.verification_status === "submitted" ? "text-bg-warning" : "text-bg-secondary"}`}>{human(row.verification_status)}</span></td><td><div className="d-flex justify-content-end gap-1 flex-wrap">{canEdit && <button className="btn btn-sm btn-outline-primary" onClick={onEdit}>Edit</button>}<button className="btn btn-sm btn-outline-secondary" onClick={onDocs}>Evidence</button>{manager && row.verification_status !== "verified" && <button className="btn btn-sm btn-outline-success" onClick={() => onVerify("verified")}>Verify</button>}{manager && row.verification_status === "submitted" && <button className="btn btn-sm btn-outline-danger" onClick={() => onVerify("rejected")}>Reject</button>}</div></td></tr>;
}
function RecordModal({ modal, setModal, meta, onClose, onSave }) {
  const { kind, form } = modal; const set = (key, value) => setModal({ ...modal, form: { ...form, [key]: value } });
  return <Modal title={`${modal.row ? "Edit" : "Add"} ${human(kind)}`} subtitle="Keep research data verification-ready for internal reporting and accreditation." onClose={onClose}><div className="row g-3">
    <Field label="Title" col="col-12"><input className="form-control" value={form.title || ""} onChange={(e) => set("title", e.target.value)} /></Field>
    <Field label="Department" col="col-md-4"><select className="form-select" value={form.department_id || ""} onChange={(e) => set("department_id", e.target.value)}><option value="">Institution-wide</option>{(meta.departments || []).map((d) => <option key={d.id} value={d.id}>{d.name}</option>)}</select></Field>
    <Field label="Academic Year" col="col-md-4"><input className="form-control" value={form.academic_year || ""} onChange={(e) => set("academic_year", e.target.value)} placeholder="2026-27" /></Field>
    <Field label="Verification" col="col-md-4"><select className="form-select" value={form.verification_status || "draft"} onChange={(e) => set("verification_status", e.target.value)}><option value="draft">Draft</option><option value="submitted">Submit for Verification</option>{meta.permissions?.manager && <option value="verified">Verified</option>}</select></Field>
    {kind === "publication" && <PublicationFields form={form} set={set} />}
    {kind === "project" && <ProjectFields form={form} set={set} />}
    {kind === "ipr" && <IprFields form={form} set={set} />}
    {kind === "activity" && <ActivityFields form={form} set={set} />}
    <Field label="External / DOI / Reference Link" col="col-12"><input className="form-control" value={form.external_url || ""} onChange={(e) => set("external_url", e.target.value)} placeholder="https://..." /></Field>
  </div><Footer onClose={onClose} onSave={onSave} /></Modal>;
}
function PublicationFields({ form, set }) { return <><Field label="Publication Type" col="col-md-4"><select className="form-select" value={form.publication_type} onChange={(e)=>set("publication_type",e.target.value)}>{["journal_article","conference_paper","book","book_chapter"].map((x)=><option key={x} value={x}>{human(x)}</option>)}</select></Field><Field label="Status" col="col-md-4"><select className="form-select" value={form.status} onChange={(e)=>set("status",e.target.value)}>{["submitted","accepted","published","rejected"].map((x)=><option key={x} value={x}>{human(x)}</option>)}</select></Field><Field label="Publication Date" col="col-md-4"><input type="date" className="form-control" value={form.publication_date || ""} onChange={(e)=>set("publication_date",e.target.value)} /></Field><Field label="Authors / Contributors" col="col-12"><textarea className="form-control" rows="2" value={form.contributors_text || ""} onChange={(e)=>set("contributors_text",e.target.value)} placeholder="Dr. A, Dr. B, Student C" /></Field><Field label="Journal / Conference" col="col-md-6"><input className="form-control" value={form.journal_conference || ""} onChange={(e)=>set("journal_conference",e.target.value)} /></Field><Field label="Publisher" col="col-md-6"><input className="form-control" value={form.publisher || ""} onChange={(e)=>set("publisher",e.target.value)} /></Field><Field label="DOI" col="col-md-4"><input className="form-control" value={form.doi || ""} onChange={(e)=>set("doi",e.target.value)} /></Field><Field label="ISSN" col="col-md-4"><input className="form-control" value={form.issn || ""} onChange={(e)=>set("issn",e.target.value)} /></Field><Field label="ISBN" col="col-md-4"><input className="form-control" value={form.isbn || ""} onChange={(e)=>set("isbn",e.target.value)} /></Field><Field label="Indexing" col="col-md-4"><input className="form-control" value={form.indexing || ""} onChange={(e)=>set("indexing",e.target.value)} placeholder="Scopus / WoS / UGC CARE..." /></Field><Field label="Impact Factor" col="col-md-4"><input type="number" step="0.001" className="form-control" value={form.impact_factor || ""} onChange={(e)=>set("impact_factor",e.target.value)} /></Field><Field label="Citations" col="col-md-4"><input type="number" min="0" className="form-control" value={form.citation_count || 0} onChange={(e)=>set("citation_count",e.target.value)} /></Field><div className="col-12 d-flex gap-4 flex-wrap">{[["scopus_indexed","Scopus"],["web_of_science_indexed","Web of Science"],["ugc_care_indexed","UGC CARE"]].map(([k,l])=><label className="form-check" key={k}><input className="form-check-input" type="checkbox" checked={!!form[k]} onChange={(e)=>set(k,e.target.checked)} /><span className="form-check-label">{l} Indexed</span></label>)}</div><Field label="Abstract / Summary" col="col-12"><textarea className="form-control" rows="3" value={form.abstract || ""} onChange={(e)=>set("abstract",e.target.value)} /></Field></>; }
function ProjectFields({ form, set }) { return <><Field label="Project Type" col="col-md-4"><select className="form-select" value={form.project_type} onChange={(e)=>set("project_type",e.target.value)}>{["funded_project","research_grant","consultancy","seed_grant","collaborative_project"].map((x)=><option key={x} value={x}>{human(x)}</option>)}</select></Field><Field label="Status" col="col-md-4"><select className="form-select" value={form.status} onChange={(e)=>set("status",e.target.value)}>{["proposed","sanctioned","ongoing","completed","closed","rejected"].map((x)=><option key={x} value={x}>{human(x)}</option>)}</select></Field><Field label="Grant Category" col="col-md-4"><select className="form-select" value={form.grant_category || ""} onChange={(e)=>set("grant_category",e.target.value)}><option value="">Select</option>{["government","private","international","internal"].map((x)=><option key={x} value={x}>{human(x)}</option>)}</select></Field><Field label="Principal Investigator" col="col-md-6"><input className="form-control" value={form.principal_investigator || ""} onChange={(e)=>set("principal_investigator",e.target.value)} /></Field><Field label="Co-Investigators" col="col-md-6"><input className="form-control" value={form.co_investigators || ""} onChange={(e)=>set("co_investigators",e.target.value)} /></Field><Field label="Funding Agency" col="col-md-6"><input className="form-control" value={form.funding_agency || ""} onChange={(e)=>set("funding_agency",e.target.value)} /></Field><Field label="Scheme / Call" col="col-md-6"><input className="form-control" value={form.scheme_name || ""} onChange={(e)=>set("scheme_name",e.target.value)} /></Field><Field label="Sanctioned Amount" col="col-md-3"><input type="number" className="form-control" value={form.sanctioned_amount || ""} onChange={(e)=>set("sanctioned_amount",e.target.value)} /></Field><Field label="Received Amount" col="col-md-3"><input type="number" className="form-control" value={form.received_amount || ""} onChange={(e)=>set("received_amount",e.target.value)} /></Field><Field label="Start Date" col="col-md-3"><input type="date" className="form-control" value={form.start_date || ""} onChange={(e)=>set("start_date",e.target.value)} /></Field><Field label="End Date" col="col-md-3"><input type="date" className="form-control" value={form.end_date || ""} onChange={(e)=>set("end_date",e.target.value)} /></Field><Field label="Summary" col="col-12"><textarea className="form-control" rows="3" value={form.summary || ""} onChange={(e)=>set("summary",e.target.value)} /></Field><Field label="Outcomes" col="col-12"><textarea className="form-control" rows="2" value={form.outcomes || ""} onChange={(e)=>set("outcomes",e.target.value)} /></Field></>; }
function IprFields({ form, set }) { return <><Field label="IPR Type" col="col-md-4"><select className="form-select" value={form.ipr_type} onChange={(e)=>set("ipr_type",e.target.value)}>{["patent","copyright","design","trademark"].map((x)=><option key={x} value={x}>{human(x)}</option>)}</select></Field><Field label="Status" col="col-md-4"><select className="form-select" value={form.status} onChange={(e)=>set("status",e.target.value)}>{["filed","published","examined","granted","rejected","abandoned"].map((x)=><option key={x} value={x}>{human(x)}</option>)}</select></Field><Field label="Country" col="col-md-4"><input className="form-control" value={form.country || ""} onChange={(e)=>set("country",e.target.value)} /></Field><Field label="Inventors / Authors" col="col-12"><input className="form-control" value={form.inventors || ""} onChange={(e)=>set("inventors",e.target.value)} /></Field><Field label="Application No." col="col-md-4"><input className="form-control" value={form.application_number || ""} onChange={(e)=>set("application_number",e.target.value)} /></Field><Field label="Filing Date" col="col-md-4"><input type="date" className="form-control" value={form.filing_date || ""} onChange={(e)=>set("filing_date",e.target.value)} /></Field><Field label="Patent / IPR Office" col="col-md-4"><input className="form-control" value={form.patent_office || ""} onChange={(e)=>set("patent_office",e.target.value)} /></Field><Field label="Publication No." col="col-md-4"><input className="form-control" value={form.publication_number || ""} onChange={(e)=>set("publication_number",e.target.value)} /></Field><Field label="Grant No." col="col-md-4"><input className="form-control" value={form.grant_number || ""} onChange={(e)=>set("grant_number",e.target.value)} /></Field><Field label="Grant Date" col="col-md-4"><input type="date" className="form-control" value={form.grant_date || ""} onChange={(e)=>set("grant_date",e.target.value)} /></Field><Field label="Remarks" col="col-12"><textarea className="form-control" rows="3" value={form.remarks || ""} onChange={(e)=>set("remarks",e.target.value)} /></Field></>; }
function ActivityFields({ form, set }) { return <><Field label="Activity Type" col="col-md-4"><select className="form-select" value={form.activity_type} onChange={(e)=>set("activity_type",e.target.value)}>{["conference","paper_presentation","fdp","workshop","seminar","invited_talk","keynote","research_methodology","award","other"].map((x)=><option key={x} value={x}>{human(x)}</option>)}</select></Field><Field label="Status" col="col-md-4"><select className="form-select" value={form.status} onChange={(e)=>set("status",e.target.value)}>{["planned","completed","cancelled"].map((x)=><option key={x} value={x}>{human(x)}</option>)}</select></Field><Field label="Role" col="col-md-4"><input className="form-control" value={form.participation_role || ""} onChange={(e)=>set("participation_role",e.target.value)} placeholder="Participant / Presenter / Keynote" /></Field><Field label="Participants" col="col-12"><input className="form-control" value={form.participant_names || ""} onChange={(e)=>set("participant_names",e.target.value)} /></Field><Field label="Organizer" col="col-md-6"><input className="form-control" value={form.organizer || ""} onChange={(e)=>set("organizer",e.target.value)} /></Field><Field label="Venue" col="col-md-6"><input className="form-control" value={form.venue || ""} onChange={(e)=>set("venue",e.target.value)} /></Field><Field label="Start Date" col="col-md-4"><input type="date" className="form-control" value={form.start_date || ""} onChange={(e)=>set("start_date",e.target.value)} /></Field><Field label="End Date" col="col-md-4"><input type="date" className="form-control" value={form.end_date || ""} onChange={(e)=>set("end_date",e.target.value)} /></Field><Field label="Certificate No." col="col-md-4"><input className="form-control" value={form.certificate_number || ""} onChange={(e)=>set("certificate_number",e.target.value)} /></Field><Field label="Remarks" col="col-12"><textarea className="form-control" rows="3" value={form.remarks || ""} onChange={(e)=>set("remarks",e.target.value)} /></Field></>; }
function EvidenceModal({ state, setState, onClose }) {
  const [file, setFile] = useState(null); const [form, setForm] = useState({ title: "", document_type: "evidence", external_url: "" }); const [busy, setBusy] = useState(false);
  const reload = async () => { const { data } = await api.get(`/research-rd/${state.kind}/${state.row.id}/documents`); setState({ ...state, documents: data?.documents || [] }); };
  const upload = async () => { if (!file && !form.external_url.trim()) return Swal.fire("Evidence required", "Choose a file or add an external link.", "warning"); setBusy(true); try { const fd = new FormData(); if (file) fd.append("file", file); Object.entries(form).forEach(([k,v]) => v && fd.append(k,v)); await api.post(`/research-rd/${state.kind}/${state.row.id}/documents`, fd, { headers: { "Content-Type": "multipart/form-data" } }); setFile(null); setForm({ title: "", document_type: "evidence", external_url: "" }); await reload(); } catch (e) { Swal.fire("Unable to add evidence", e.response?.data?.message || e.message, "error"); } finally { setBusy(false); } };
  const download = async (doc) => { if (doc.external_url && !doc.file_path) return window.open(doc.external_url, "_blank", "noopener,noreferrer"); try { const response = await api.get(`/research-rd/${state.kind}/${state.row.id}/documents/${doc.id}/download`, { responseType: "blob" }); const url = URL.createObjectURL(response.data); const a = document.createElement("a"); a.href = url; a.download = doc.original_name || doc.title || "research-evidence"; a.click(); URL.revokeObjectURL(url); } catch (e) { Swal.fire("Unable to download", e.response?.data?.message || e.message, "error"); } };
  return <Modal title="Research Evidence" subtitle={state.row.title} onClose={onClose}><div className="row g-2 mb-4"><Field label="Evidence Type" col="col-md-3"><select className="form-select" value={form.document_type} onChange={(e)=>setForm({...form,document_type:e.target.value})}>{["evidence","paper","acceptance_letter","grant_letter","certificate","patent_document","report","other"].map((x)=><option key={x} value={x}>{human(x)}</option>)}</select></Field><Field label="Title" col="col-md-3"><input className="form-control" value={form.title} onChange={(e)=>setForm({...form,title:e.target.value})} /></Field><Field label="File (max 50 MB)" col="col-md-3"><input type="file" className="form-control" onChange={(e)=>setFile(e.target.files?.[0] || null)} /></Field><Field label="External Link" col="col-md-3"><input className="form-control" value={form.external_url} onChange={(e)=>setForm({...form,external_url:e.target.value})} placeholder="https://..." /></Field><div className="col-12 text-end"><button className="btn btn-primary" disabled={busy} onClick={upload}>{busy ? "Adding..." : "Add Evidence"}</button></div></div><div className="list-group">{state.documents.length ? state.documents.map((d)=><button key={d.id} className="list-group-item list-group-item-action d-flex justify-content-between align-items-center" onClick={()=>download(d)}><span><i className="bi bi-paperclip me-2" />{d.title || d.original_name || human(d.document_type)}</span><small className="text-muted">{date(String(d.createdAt || "").slice(0,10))}</small></button>) : <div className="text-muted text-center py-4">No evidence uploaded yet.</div>}</div></Modal>;
}
function Modal({ title, subtitle, onClose, children }) { return <div className="research-backdrop"><div className="research-modal"><div className="research-modal-head"><div><span className="research-kicker">Research & Publications</span><h2 className="h4 mb-1">{title}</h2>{subtitle && <p className="mb-0">{subtitle}</p>}</div><button className="btn-close" onClick={onClose} /></div><div className="research-modal-body">{children}</div></div></div>; }
function Field({ label, col="col-12", children }) { return <div className={col}><label className="form-label">{label}</label>{children}</div>; }
function Footer({ onClose, onSave }) { return <div className="d-flex justify-content-end gap-2 mt-4"><button className="btn btn-light" onClick={onClose}>Cancel</button><button className="btn btn-primary" onClick={onSave}>Save Research Record</button></div>; }
