import React,{useCallback,useEffect,useMemo,useState} from "react";
import Swal from "sweetalert2";
import api from "../api";
import {useInstitution} from "../institution/InstitutionContext";
import "./StudentClubsActivities.css";

const roles=()=>{try{const a=JSON.parse(localStorage.getItem("roles")||"[]");const b=localStorage.getItem("userRole");return(a.length?a:[b]).filter(Boolean).map(x=>String(x).toLowerCase());}catch(_){return[String(localStorage.getItem("userRole")||"").toLowerCase()].filter(Boolean);}};
const MANAGER=new Set(["department_hod","principal","academic_coordinator","coordinator","admin","superadmin","super_admin"]);
const STAFF=new Set(["teacher",...MANAGER]);
const human=v=>String(v||"").replace(/_/g," ").replace(/\b\w/g,m=>m.toUpperCase());
const d=v=>v?new Date(`${String(v).slice(0,10)}T00:00:00`).toLocaleDateString([], {dateStyle:"medium"}):"—";
const n=v=>Number(v||0).toLocaleString(undefined,{maximumFractionDigits:1});

export default function StudentClubsActivities(){
  const rr=roles(),staff=rr.some(x=>STAFF.has(x)),manager=rr.some(x=>MANAGER.has(x)),student=rr.includes("student");
  const {isCollege}=useInstitution();
  const [loading,setLoading]=useState(true),[tab,setTab]=useState("overview");
  const [meta,setMeta]=useState({classes:[],sections:[],employees:[]}),[dash,setDash]=useState({counts:{},standings:[]}),[clubs,setClubs]=useState([]),[events,setEvents]=useState([]),[mine,setMine]=useState(null),[report,setReport]=useState([]);
  const [query,setQuery]=useState("");
  const labels={title:isCollege?"Clubs, Societies & Activities":"Clubs, Houses & Activities",club:isCollege?"Club / Society":"Club / House",className:isCollege?"Program / Semester":"Class",section:isCollege?"Batch / Section":"Section"};
  const load=useCallback(async()=>{setLoading(true);try{
    const calls=[api.get("/student-activities/meta"),api.get("/student-activities/dashboard"),api.get("/student-activities/clubs"),api.get("/student-activities/events")];
    const [m,da,c,e]=await Promise.all(calls);setMeta(m.data||{});setDash(da.data||{});setClubs(c.data?.clubs||[]);setEvents(e.data?.events||[]);
    if(student){const x=await api.get("/student-activities/my-activity").catch(()=>({data:null}));setMine(x.data||null);}
    if(manager){const x=await api.get("/student-activities/report").catch(()=>({data:{rows:[]}}));setReport(x.data?.rows||[]);}
  }catch(e){Swal.fire("Unable to load",e.response?.data?.message||e.message,"error");}finally{setLoading(false);}},[student,manager]);
  useEffect(()=>{load();},[load]);
  const filteredClubs=useMemo(()=>clubs.filter(x=>!query||`${x.name} ${x.club_type} ${x.description||""}`.toLowerCase().includes(query.toLowerCase())),[clubs,query]);
  if(loading)return <div className="container-fluid py-5 text-center"><span className="spinner-border spinner-border-sm me-2"/>Loading clubs & activities…</div>;
  const tabs=["overview","clubs","events",...(student?["my activities"]:[]),...(manager?["reports"]:[])];
  return <div className="container-fluid py-4 student-activities-page">
    <Hero isCollege={isCollege}/>
    <div className="activity-tabs mb-4">{tabs.map(x=><button key={x} className={tab===x?"active":""} onClick={()=>setTab(x)}>{human(x)}</button>)}</div>
    {tab==="overview"&&<Overview dash={dash} isCollege={isCollege} events={events}/>} 
    {tab==="clubs"&&<Clubs labels={labels} rows={filteredClubs} query={query} setQuery={setQuery} student={student} staff={staff} manager={manager} meta={meta} onCreate={()=>createClub(meta,labels,load,isCollege)} onJoin={async id=>{try{const {data}=await api.post(`/student-activities/clubs/${id}/join`);Swal.fire("Done",data.message||"Request submitted.","success");load();}catch(e){Swal.fire("Unable to join",e.response?.data?.message||e.message,"error");}}} onMembers={id=>showMembers(id,load)} />}
    {tab==="events"&&<Events labels={labels} rows={events} clubs={clubs} meta={meta} student={student} staff={staff} onCreate={()=>createEvent(meta,clubs,labels,load,isCollege)} onRegister={async ev=>{const houses=clubs.filter(c=>["house","house_team"].includes(c.club_type));let representing=null;if(ev.is_inter_house&&houses.length){const {value}=await Swal.fire({title:"Representing House / Team",input:"select",inputOptions:Object.fromEntries([["","Select"],...houses.map(h=>[h.id,h.name])]),showCancelButton:true});if(value===undefined)return;representing=value||null;}try{await api.post(`/student-activities/events/${ev.id}/register`,{representing_club_id:representing});Swal.fire("Registered","Event registration completed.","success");load();}catch(e){Swal.fire("Unable to register",e.response?.data?.message||e.message,"error");}}} onParticipants={id=>manageParticipants(id,clubs,load)}/>} 
    {tab==="my activities"&&student&&<MyActivity data={mine}/>} 
    {tab==="reports"&&manager&&<Reports rows={report}/>} 
  </div>;
}

function Hero({isCollege}){return <div className="activities-hero mb-4"><div><span>{isCollege?"Student Engagement · Leadership · Co-Curricular":"Student Engagement · Houses · Co-Curricular"}</span><h1>{isCollege?"Clubs, Societies & Activities":"Clubs, Houses & Activities"}</h1><p>{isCollege?"Manage societies, student memberships, events, participation, activity hours, achievements and certificates in one place.":"Manage clubs, houses, memberships, events, competitions, house points, participation and student activity records in one place."}</p></div><i className="bi bi-trophy-fill"/></div>}
function Metric({icon,label,value,tone="primary"}){return <div className="col-6 col-xl-2 col-lg-4"><div className={`activity-metric ${tone}`}><i className={`bi ${icon}`}/><strong>{n(value)}</strong><small>{label}</small></div></div>}
function Overview({dash,isCollege,events}){const c=dash.counts||{},up=events.filter(x=>x.status==="published").slice(0,5);return <><div className="row g-3 mb-4"><Metric icon="bi-people-fill" label={isCollege?"Active Clubs":"Clubs / Houses"} value={c.clubs}/><Metric icon="bi-person-check-fill" label="Active Members" value={c.active_members} tone="success"/><Metric icon="bi-calendar-event" label="Upcoming Events" value={c.upcoming_events} tone="warning"/><Metric icon="bi-award-fill" label="Participations" value={c.participations} tone="info"/><Metric icon="bi-stars" label="Activity Points" value={c.total_points} tone="violet"/><Metric icon="bi-clock-history" label="Activity Hours" value={c.activity_hours} tone="dark"/></div><div className="row g-4"><div className="col-xl-7"><div className="card border-0 shadow-sm h-100"><div className="card-body p-4"><h2 className="h5 mb-3">Upcoming / Recent Activities</h2>{up.map(x=><div className="activity-row" key={x.id}><div><strong>{x.title}</strong><small>{d(x.event_date)} · {x.venue||"Venue TBA"} · {x.club?.name||"Institution Activity"}</small></div><span className="badge text-bg-light border">{human(x.event_type)}</span></div>)}{!up.length&&<Empty text="No published activities yet."/>}</div></div></div><div className="col-xl-5"><div className="card border-0 shadow-sm h-100"><div className="card-body p-4"><h2 className="h5 mb-3">{isCollege?"Activity / Society Standings":"House Standings"}</h2>{(dash.standings||[]).map((x,i)=><div className="standing-row" key={x.club_id}><span className="standing-rank">#{i+1}</span><div><strong>{x.name}</strong><small>{n(x.activity_hours)} activity hrs · {n(x.service_hours)} service hrs</small></div><b>{n(x.points)} pts</b></div>)}{!(dash.standings||[]).length&&<Empty text={isCollege?"Create House/Team type groups to show standings here.":"Create house groups and record event points to build standings."}/>}</div></div></div></div></>}

function Clubs({labels,rows,query,setQuery,student,manager,meta,onCreate,onJoin,onMembers}){return <div className="card border-0 shadow-sm"><div className="card-body p-4"><div className="d-flex flex-wrap justify-content-between gap-3 mb-3"><div><h2 className="h5 mb-1">{labels.club}s</h2><p className="text-muted small mb-0">Membership, coordinators, student leaders and club/house participation.</p></div><div className="d-flex gap-2"><input className="form-control" placeholder="Search clubs…" value={query} onChange={e=>setQuery(e.target.value)}/>{manager&&<button className="btn btn-primary text-nowrap" onClick={onCreate}>+ Create {labels.club}</button>}</div></div><div className="row g-3">{rows.map(c=><div className="col-xl-4 col-md-6" key={c.id}><div className="club-card h-100"><div className="d-flex justify-content-between gap-2"><span className={`club-type ${c.club_type}`}>{human(c.club_type)}</span><span className={`badge ${c.is_active?"text-bg-success":"text-bg-secondary"}`}>{c.is_active?"Active":"Inactive"}</span></div><h3>{c.name}</h3><p>{c.description||"No description added yet."}</p><div className="club-facts"><span><i className="bi bi-people"/> {c.member_count||0} members</span><span><i className="bi bi-person-badge"/> {c.facultyCoordinator?.name||"Coordinator TBA"}</span>{c.capacity&&<span><i className="bi bi-person-lines-fill"/> Capacity {c.capacity}</span>}</div><div className="d-flex gap-2 mt-auto pt-3">{student&&!c.my_membership&&c.join_policy!=="invite"&&<button className="btn btn-sm btn-primary" onClick={()=>onJoin(c.id)}>Join / Apply</button>}{student&&c.my_membership&&<span className="badge text-bg-light border align-self-center">{human(c.my_membership.status)}</span>}{!student&&<button className="btn btn-sm btn-outline-primary" onClick={()=>onMembers(c.id)}>Members</button>}</div></div></div>)}{!rows.length&&<Empty text="No clubs / houses match your search."/>}</div></div></div>}

function Events({rows,clubs,student,staff,onCreate,onRegister,onParticipants}){return <div className="card border-0 shadow-sm"><div className="card-body p-4"><div className="d-flex justify-content-between mb-3"><div><h2 className="h5 mb-1">Events, Competitions & Activities</h2><p className="text-muted small mb-0">Registrations, attendance, winners, points, activity/service hours and certificates.</p></div>{staff&&<button className="btn btn-primary" onClick={onCreate}>+ Create Activity</button>}</div>{rows.map(ev=><div className="event-card" key={ev.id}><div className="event-date"><b>{new Date(`${ev.event_date}T00:00:00`).getDate()}</b><span>{new Date(`${ev.event_date}T00:00:00`).toLocaleString([], {month:"short"})}</span></div><div className="flex-grow-1"><div className="d-flex flex-wrap align-items-center gap-2"><h3>{ev.title}</h3><span className={`badge ${ev.status==="published"?"text-bg-success":ev.status==="completed"?"text-bg-primary":"text-bg-secondary"}`}>{human(ev.status)}</span>{ev.is_inter_house&&<span className="badge text-bg-warning">Inter-House / Team</span>}</div><small>{ev.club?.name||"Institution Activity"} · {ev.venue||"Venue TBA"} · {ev.participant_count||0} registrations</small><p>{ev.description}</p></div><div className="event-actions">{student&&ev.status==="published"&&!ev.my_registration&&<button className="btn btn-sm btn-primary" onClick={()=>onRegister(ev)}>Register</button>}{student&&ev.my_registration&&<span className="badge text-bg-light border">{human(ev.my_registration.registration_status)}</span>}{staff&&<button className="btn btn-sm btn-outline-primary" onClick={()=>onParticipants(ev.id)}>Participants</button>}{ev.gallery_link&&<a className="btn btn-sm btn-outline-secondary" href={ev.gallery_link} target="_blank" rel="noreferrer">Gallery</a>}</div></div>)}{!rows.length&&<Empty text="No activities created yet."/>}</div></div>}

function MyActivity({data}){const s=data?.summary||{};return <><div className="row g-3 mb-4"><Metric icon="bi-stars" label="Points" value={s.points}/><Metric icon="bi-clock" label="Activity Hours" value={s.activity_hours} tone="info"/><Metric icon="bi-heart-fill" label="Service Hours" value={s.service_hours} tone="success"/><Metric icon="bi-calendar-check" label="Events Attended" value={s.attended} tone="warning"/><Metric icon="bi-award" label="Achievements" value={s.achievements} tone="violet"/><Metric icon="bi-patch-check" label="Certificates" value={s.certificates} tone="dark"/></div><div className="row g-4"><div className="col-lg-5"><div className="card border-0 shadow-sm"><div className="card-body p-4"><h2 className="h5">My Clubs / Houses</h2>{(data?.memberships||[]).map(x=><div className="activity-row" key={x.id}><div><strong>{x.club?.name||"Club"}</strong><small>{human(x.member_role)} · {human(x.status)}</small></div></div>)}{!(data?.memberships||[]).length&&<Empty text="You have not joined any clubs yet."/>}</div></div></div><div className="col-lg-7"><div className="card border-0 shadow-sm"><div className="card-body p-4"><h2 className="h5">Participation & Achievements</h2>{(data?.participations||[]).map(x=><div className="activity-row" key={x.id}><div><strong>{x.event?.title||"Activity"}</strong><small>{x.event?.event_date?d(x.event.event_date):""} · {human(x.attendance_status)}</small>{x.position&&<span className="achievement-line"><i className="bi bi-trophy-fill"/> {x.position}</span>}</div><div className="text-end"><b>{n(x.points)} pts</b><small className="d-block">{n(x.activity_hours)} hrs</small>{x.certificate_issued&&<span className="badge text-bg-success">Certificate</span>}</div></div>)}{!(data?.participations||[]).length&&<Empty text="Your activity participation will appear here."/>}</div></div></div></div></>}
function Reports({rows}){return <div className="card border-0 shadow-sm"><div className="card-body p-4"><h2 className="h5">Club / House Activity Report</h2><div className="table-responsive"><table className="table align-middle"><thead><tr><th>Club / House</th><th>Type</th><th>Members</th><th>Events</th><th>Points</th><th>Activity Hours</th><th>Service Hours</th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td><strong>{x.name}</strong></td><td>{human(x.club_type)}</td><td>{x.members}</td><td>{x.events}</td><td>{n(x.points)}</td><td>{n(x.activity_hours)}</td><td>{n(x.service_hours)}</td></tr>)}</tbody></table></div>{!rows.length&&<Empty text="No activity report data yet."/>}</div></div>}
function Empty({text}){return <div className="empty-activity"><i className="bi bi-inbox"/><span>{text}</span></div>}

async function createClub(meta,labels,refresh,isCollege){const employees=meta.employees||[];const options=employees.map(x=>`<option value="${x.id}">${x.name}${x.designation?` · ${x.designation}`:""}</option>`).join("");const types=isCollege?'<option value="club">Club</option><option value="society">Society</option><option value="cell">Cell</option><option value="nss">NSS</option><option value="ncc">NCC</option><option value="sports">Sports Club</option><option value="house_team">House / Team</option>':'<option value="club">Club</option><option value="house">House</option><option value="sports">Sports</option><option value="nss">NSS</option><option value="ncc">NCC</option><option value="society">Society</option>';const {value:v}=await Swal.fire({title:`Create ${labels.club}`,width:720,html:`<input id="ca-name" class="swal2-input" placeholder="Name"><select id="ca-type" class="swal2-select">${types}</select><select id="ca-coord" class="swal2-select"><option value="">Faculty coordinator</option>${options}</select><select id="ca-policy" class="swal2-select"><option value="approval">Join with approval</option><option value="open">Open join</option><option value="invite">Invite only</option></select><input id="ca-cap" type="number" class="swal2-input" placeholder="Capacity (optional)"><textarea id="ca-desc" class="swal2-textarea" placeholder="Purpose / description"></textarea>`,showCancelButton:true,confirmButtonText:"Create",preConfirm:()=>({name:document.getElementById("ca-name").value,club_type:document.getElementById("ca-type").value,faculty_coordinator_employee_id:document.getElementById("ca-coord").value||null,join_policy:document.getElementById("ca-policy").value,capacity:document.getElementById("ca-cap").value||null,description:document.getElementById("ca-desc").value})});if(v){try{await api.post("/student-activities/clubs",v);Swal.fire("Created",`${labels.club} created successfully.`,"success");refresh();}catch(e){Swal.fire("Unable to create",e.response?.data?.message||e.message,"error");}}}
async function createEvent(meta,clubs,labels,refresh,isCollege){const clubOptions=clubs.filter(c=>c.is_active).map(c=>`<option value="${c.id}">${c.name}</option>`).join("");const classOptions=(meta.classes||[]).map(c=>`<option value="${c.id}">${c.class_name}</option>`).join("");const types='<option value="activity">Activity</option><option value="competition">Competition</option><option value="workshop">Workshop</option><option value="guest_lecture">Guest Lecture</option><option value="cultural">Cultural</option><option value="sports">Sports</option><option value="community_service">Community Service</option><option value="nss_ncc">NSS / NCC</option>';const {value:v}=await Swal.fire({title:"Create Activity / Event",width:760,html:`<input id="ev-title" class="swal2-input" placeholder="Event / activity title"><select id="ev-club" class="swal2-select"><option value="">Institution-wide activity</option>${clubOptions}</select><select id="ev-type" class="swal2-select">${types}</select><input id="ev-date" type="date" class="swal2-input"><input id="ev-venue" class="swal2-input" placeholder="Venue / location"><select id="ev-class" class="swal2-select"><option value="">All ${labels.className}s</option>${classOptions}</select><input id="ev-max" type="number" class="swal2-input" placeholder="Max participants (optional)"><textarea id="ev-desc" class="swal2-textarea" placeholder="Description"></textarea><label class="swal2-checkbox"><input id="ev-house" type="checkbox"> ${isCollege?"Team / house points event":"Inter-house points event"}</label><label class="swal2-checkbox"><input id="ev-publish" type="checkbox" checked> Publish & notify students</label>`,showCancelButton:true,confirmButtonText:"Create",preConfirm:()=>({title:document.getElementById("ev-title").value,club_id:document.getElementById("ev-club").value||null,event_type:document.getElementById("ev-type").value,event_date:document.getElementById("ev-date").value,venue:document.getElementById("ev-venue").value,target_class_id:document.getElementById("ev-class").value||null,max_participants:document.getElementById("ev-max").value||null,description:document.getElementById("ev-desc").value,is_inter_house:document.getElementById("ev-house").checked,status:document.getElementById("ev-publish").checked?"published":"draft"})});if(v){try{await api.post("/student-activities/events",v);Swal.fire("Created","Activity created successfully.","success");refresh();}catch(e){Swal.fire("Unable to create",e.response?.data?.message||e.message,"error");}}}
async function showMembers(clubId,refresh){try{const {data}=await api.get(`/student-activities/clubs/${clubId}/members`);const rows=data.members||[];if(!rows.length)return Swal.fire("No members","No memberships yet.","info");const html=`<div style="max-height:420px;overflow:auto;text-align:left">${rows.map(m=>`<div style="padding:10px;border-bottom:1px solid #eee"><b>${m.student?.name||"Student"}</b><br><small>${m.student?.admission_number||""} · ${human(m.member_role)} · ${human(m.status)}</small><div style="margin-top:8px"><button class="swal2-styled club-member-action" data-id="${m.id}" data-status="active" style="background:#198754">Approve</button><button class="swal2-styled club-member-action" data-id="${m.id}" data-status="rejected" style="background:#6c757d">Reject</button></div></div>`).join("")}</div>`;await Swal.fire({title:"Club Members",width:700,html,showConfirmButton:false,showCloseButton:true,didOpen:()=>{document.querySelectorAll(".club-member-action").forEach(b=>b.addEventListener("click",async()=>{await api.patch(`/student-activities/clubs/${clubId}/members/${b.dataset.id}`,{status:b.dataset.status});Swal.close();refresh();}));}});}catch(e){Swal.fire("Unable to load members",e.response?.data?.message||e.message,"error");}}
async function manageParticipants(eventId,clubs,refresh){try{const {data}=await api.get(`/student-activities/events/${eventId}/participants`);const rows=data.participants||[];if(!rows.length)return Swal.fire("No participants","No students have registered yet.","info");const houseOpts=clubs.filter(c=>["house","house_team"].includes(c.club_type)).map(c=>`<option value="${c.id}">${c.name}</option>`).join("");const html=`<div style="max-height:500px;overflow:auto;text-align:left">${rows.map(p=>`<div style="padding:12px;border-bottom:1px solid #eee"><b>${p.student?.name||"Student"}</b><br><small>${p.student?.admission_number||""}</small><div style="display:grid;grid-template-columns:repeat(3,1fr);gap:6px;margin-top:8px"><select class="form-select p-att" data-id="${p.id}"><option value="pending" ${p.attendance_status==="pending"?"selected":""}>Pending</option><option value="present" ${p.attendance_status==="present"?"selected":""}>Present</option><option value="absent" ${p.attendance_status==="absent"?"selected":""}>Absent</option></select><input class="form-control p-pos" data-id="${p.id}" placeholder="Position" value="${p.position||""}"><input class="form-control p-points" data-id="${p.id}" type="number" step="0.5" placeholder="Points" value="${p.points||0}"><input class="form-control p-hours" data-id="${p.id}" type="number" step="0.5" placeholder="Activity hrs" value="${p.activity_hours||0}"><input class="form-control p-service" data-id="${p.id}" type="number" step="0.5" placeholder="Service hrs" value="${p.service_hours||0}"><select class="form-select p-club" data-id="${p.id}"><option value="">Representing team</option>${houseOpts}</select></div><button class="swal2-styled p-save" data-id="${p.id}" style="background:#0d6efd;margin-top:8px">Save Result</button></div>`).join("")}</div>`;await Swal.fire({title:"Participants & Results",width:900,html,showConfirmButton:false,showCloseButton:true,didOpen:()=>{document.querySelectorAll(".p-save").forEach(b=>b.addEventListener("click",async()=>{const id=b.dataset.id;const get=(cls)=>document.querySelector(`${cls}[data-id="${id}"]`);await api.patch(`/student-activities/events/${eventId}/participants/${id}`,{attendance_status:get(".p-att").value,position:get(".p-pos").value,points:get(".p-points").value,activity_hours:get(".p-hours").value,service_hours:get(".p-service").value,representing_club_id:get(".p-club").value||null});b.textContent="Saved ✓";setTimeout(()=>b.textContent="Save Result",1200);}));}});refresh();}catch(e){Swal.fire("Unable to load participants",e.response?.data?.message||e.message,"error");}}
